# Draw keymap diagrams using keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - 'boards/*.keymap'
      - 'boards/includes/*.dtsi'
      - keymap-drawer/config.yaml
      - .github/workflows/draw-keymaps.yml

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      keymap_patterns: 'boards/shields/*.keymap'
      config_path: keymap-drawer/config.yaml
      output_folder: keymap-drawer
      install_branch: main
      amend_commit: true
      draw_args: "bykeeb:'-k obosob/arch_36'"
      json_path: keymap-drawer/layouts